documentation:
- changed-files:
  - any-glob-to-any-file: ['doc/source/**/*', 'examples/**/*', 'README.md']

maintenance:
- changed-files:
  - any-glob-to-any-file: ['.github/**/*', 'codecov.yml', '.flake8', 'pyproject.toml']

dependencies:
- changed-files:
  - any-glob-to-any-file: ['pyproject.toml']

ci/cd:
- changed-files:
  - any-glob-to-any-file: ['docker/**/*', '.github/**/*', '.ci/**/*']

testing:
- changed-files:
  - any-glob-to-any-file: ['tests/**/*',]

grpc-transition:
- changed-files:
  - any-glob-to-any-file: ['src/pyedb/dotnet/database/*',]
