name: GitHub CI - PR

# Run only on when pushing into this branch
on:
  push:
    branches:
      - release/26R1-sp

env:
  MAIN_PYTHON_VERSION: '3.12'
  PACKAGE_NAME: 'pyedb'
  ON_CI: True

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  
  package:
    name: Package library
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Install Git and clone project
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: Set up uv
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
        with:
          enable-cache: false
          prune-cache: true

      - name: Create virtual environment
        run: uv venv .venv

      - name: Install custom ansys-api-edb and pyedb-core
        shell: bash
        run: |
          source .venv/bin/activate
          uv pip install .ci/ansys-api-edb/ansys_api_edb-0.3.1.261.0-py3-none-any.whl
          uv pip install .ci/ansys-edb-core/ansys_edb_core-0.3.1.261.0-py3-none-any.whl
          uv pip install .

      - name: Install build
        shell: bash
        run: |
          source .venv/bin/activate
          uv pip install build

      - name: Build distribution artifacts
        shell: bash
        run: |
          source .venv/bin/activate
          python -m build .

      - name: Upload packages
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.3
        with:
          name: ansys-edb-core-package
          path: dist/
          retention-days: 7

      - name: Build library source and wheel artifacts
        uses: ansys/actions/build-library@7d55ff0b9f67c77dae50a286d711ee1ae27b0a25 # v10.2.12
        with:
          library-name: ${{ env.PACKAGE_NAME }}
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          attest-provenance: true
