name: GitHub CI - PR

on:
  pull_request:

env:
  ANSYSLMD_LICENSE_FILE: ${{ format('1055@{0}', secrets.LICENSE_SERVER) }}
  MAIN_PYTHON_VERSION: '3.14'
  ON_CI: True
  PACKAGE_NAME: 'pyedb'
  PYEDB_CI_NO_DISPLAY: '1'
  TESTS_VERSION: '3.10'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  
  pr-title:
    name: Check the title of the pull request
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check the title of the pull request
        uses: ansys/actions/check-pr-title@d946b24b9a765f4169bcc94afdb27bd1a0533741 # v10.3.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          use-upper-case: true

  vulnerabilities:
    name: Vulnerabilities
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: ansys/actions/check-vulnerabilities@d946b24b9a765f4169bcc94afdb27bd1a0533741 # v10.3.2
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          python-package-name: ${{ env.PACKAGE_NAME }}
          token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
          dev-mode: true

  actions-security:
    name: Check actions security
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: ansys/actions/check-actions-security@a5b0351dc277d68c2dc1beca2d2674c7dfa4fc55 # v10.3.3
        with:
          generate-summary: true
          token: ${{ secrets.GITHUB_TOKEN }}
          auditing-level: 'high'

  doc-style:
    name: Documentation style check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check documentation style
        uses: ansys/actions/doc-style@d946b24b9a765f4169bcc94afdb27bd1a0533741 # v10.3.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  smoke-tests:
    name: Build and Smoke tests (${{ matrix.os }} | Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    permissions:
      attestations: write # Required to create and publish build attestations (SLSA provenance)
      contents: read
      id-token: write # Required for OIDC token generation (for provenance signing)
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
    steps:
      - name: Build wheelhouse and perform smoke test
        id: build-wheelhouse
        uses: ansys/actions/build-wheelhouse@a5b0351dc277d68c2dc1beca2d2674c7dfa4fc55 # v10.3.3
        with:
          library-name: ${{ env.PACKAGE_NAME }}
          operating-system: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}
          attest-provenance: true
          target: 'all'

      - name: Import python package
        shell: bash
        env:
          ACTIVATE_VENV: ${{ steps.build-wheelhouse.outputs.activate-venv }}
        run: |
          ${ACTIVATE_VENV}
          python -c "import pyedb; from pyedb import __version__"

  unit-tests-dotnet:
    name: Unit test dotnet
    needs: [smoke-tests]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      ANSYSEM_ROOT261: '/usr/ansys_inc/v261/AnsysEM'
      ANS_NODEPCHECK: '1'
      USE_GRPC: '0'
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ env.TESTS_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: false

      - name: Install Python library and tests dependencies
        run: uv sync --frozen --extra all --group tests --extra dotnet

      - name: Run unit tests
        run: |
          source .venv/bin/activate
          pytest tests/unit -vvv --cov=pyedb --color=yes -ra

      - name: Create coverage files
        run: |
          source .venv/bin/activate
          python -m coverage html -d .cov\unit-html
          python -m coverage xml -o .cov\unit.xml

      - name: Upload Coverage Results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: .cov\unit-html
          name: html-unit-coverage-${{ github.job }}-${{ github.run_attempt }}
          retention-days: 7

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: .cov/unit.xml

  unit-tests-grpc:
    name: Unit test grpc
    needs: [smoke-tests]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      ANSYSEM_ROOT261: '/usr/ansys_inc/v261/AnsysEM'
      ANS_NODEPCHECK: '1'
      USE_GRPC: '1'
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ env.TESTS_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: false

      - name: Install Python library and tests dependencies
        run: uv sync --frozen --extra all --group tests

      - name: Run unit tests
        run: |
          source .venv/bin/activate
          pytest tests/unit -vvv --cov=pyedb --color=yes -ra

      - name: Create coverage files
        run: |
          source .venv/bin/activate
          python -m coverage html -d .cov\unit-html
          python -m coverage xml -o .cov\unit.xml

      - name: Upload Coverage Results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: .cov\unit-html
          name: html-unit-coverage-${{ github.job }}-${{ github.run_attempt }}
          retention-days: 7

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: .cov/unit.xml

# =================================================================================================
# vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv    RUNNING ON SELF-HOSTED RUNNER    vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
# =================================================================================================
  
  system-tests-windows-dotnet:
    name: Test dotnet (windows)
    needs: [unit-tests-dotnet]
    runs-on: [ Windows, self-hosted, pyedb ]
    permissions:
      contents: read
    env:
      USE_GRPC: '0'
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ env.TESTS_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: false

      - name: Install Python library and tests dependencies
        run: uv sync --frozen --extra all --group tests --extra dotnet


      - name: Executing system tests
        run: |
          .venv\Scripts\activate
          pytest tests/system --cov=pyedb --color=yes -ra
        timeout-minutes: 60


      - name: Create coverage files
        run: |
          .venv\Scripts\activate
          python -m coverage html -d .cov\system-html
          python -m coverage xml -o .cov\system.xml

      - name: Upload Coverage Results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: .cov\system-html
          name: html-system-coverage-${{ github.job }}-${{ github.run_attempt }}
          retention-days: 7

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: .cov/system.xml

# =================================================================================================
# vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv    RUNNING ON SELF-HOSTED RUNNER    vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
# =================================================================================================

  system-tests-windows-grpc:
    name: Test grpc (windows)
    needs: [unit-tests-grpc]
    runs-on: [ Windows, self-hosted, pyedb ]
    permissions:
      contents: read
    env:
      USE_GRPC: '1'
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ env.TESTS_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: false

      - name: Install Python library and tests dependencies
        run: uv sync --frozen --extra all --group tests


      - name: Executing system tests
        run: |
          .venv\Scripts\activate
          pytest tests/system --cov=pyedb --color=yes -ra
        timeout-minutes: 180


      - name: Create coverage files
        run: |
          .venv\Scripts\activate
          python -m coverage html -d .cov\system-html
          python -m coverage xml -o .cov\system.xml

      - name: Upload Coverage Results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: .cov\system-html
          name: html-system-coverage-${{ github.job }}-${{ github.run_attempt }}
          retention-days: 7

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: .cov/system.xml

# =================================================================================================
# vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv    RUNNING ON SELF-HOSTED RUNNER    vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
# =================================================================================================

  system-tests-linux-dotnet:
    name: Test dotnet (linux)
    needs: [unit-tests-dotnet]
    runs-on: [ Linux, self-hosted, pyedb ]
    permissions:
      contents: read
    env:
      ANSYSEM_ROOT261: '/usr/ansys_inc/v261/AnsysEM'
      ANS_NODEPCHECK: '1'
      USE_GRPC: '0'
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install os packages
        run: |
          sudo apt update
          sudo apt install libgl1-mesa-glx -y

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ env.TESTS_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: false

      - name: Install Python library and tests dependencies
        run: uv sync --frozen --extra all --group tests --extra dotnet


      - name: Executing system tests
        run: |
          source .venv/bin/activate
          pytest tests/system --cov=pyedb --color=yes -ra
        timeout-minutes: 180


      - name: Create coverage files
        run: |
          source .venv/bin/activate
          python -m coverage html -d .cov/system-html
          python -m coverage xml -o .cov/system.xml

      - name: Upload Coverage Results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: .cov/system-html
          name: html-system-linux-coverage-${{ github.job }}-${{ github.run_attempt }}
          retention-days: 7

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: .cov/system.xml

# =================================================================================================
# vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv    RUNNING ON SELF-HOSTED RUNNER    vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
# =================================================================================================

  system-tests-linux-grpc:
    name: Test grpc (linux)
    needs: [unit-tests-grpc]
    runs-on: [ Linux, self-hosted, pyedb ]
    permissions:
      contents: read
    env:
      ANSYSEM_ROOT261: '/usr/ansys_inc/v261/AnsysEM'
      ANS_NODEPCHECK: '1'
      USE_GRPC: '1'
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install os packages
        run: |
          sudo apt update
          sudo apt install libgl1-mesa-glx -y

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ env.TESTS_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: false

      - name: Install Python library and tests dependencies
        run: uv sync --frozen --extra all --group tests


      - name: Executing system tests
        run: |
          source .venv/bin/activate
          pytest tests/system --cov=pyedb --color=yes -ra
        timeout-minutes: 180


      - name: Create coverage files
        run: |
          source .venv/bin/activate
          python -m coverage html -d .cov/system-html
          python -m coverage xml -o .cov/system.xml

      - name: Upload Coverage Results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: .cov/system-html
          name: html-system-linux-coverage-${{ github.job }}-${{ github.run_attempt }}
          retention-days: 7

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: .cov/system.xml

  docs-build:
    name: Build documentation
    needs: [doc-style]
    runs-on: ubuntu-latest
    steps:
      - name: Build documentation
        uses: ansys/actions/doc-build@a5b0351dc277d68c2dc1beca2d2674c7dfa4fc55 # v10.3.3
        with:
          dependencies: "graphviz texlive-latex-extra latexmk texlive-xetex texlive-fonts-extra"
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          sphinxopts: '-j 1 --color -w build_errors.txt'
          use-python-cache: false
          check-links: false
          needs-quarto: true
          group-dependencies-name: 'doc'

  package:
    name: Package library
    needs: [system-tests-windows-dotnet,
            system-tests-windows-grpc,
            system-tests-linux-dotnet,
            system-tests-linux-grpc,
            docs-build]
    runs-on: ubuntu-latest
    permissions:
      attestations: write # Required to create and publish package attestations (SLSA provenance)
      contents: read
      id-token: write # Required for OIDC token generation (for provenance signing)
    steps:
      - name: Build library source and wheel artifacts
        uses: ansys/actions/build-library@a5b0351dc277d68c2dc1beca2d2674c7dfa4fc55 # v10.3.3
        with:
          library-name: ${{ env.PACKAGE_NAME }}
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          attest-provenance: true
