name: Labeler

on:
  pull_request:
      # opened, reopened, and synchronize are default for pull_request
      # edited - when PR title or body is changed
      # labeled - when labels are added to PR
      types: [opened, reopened, synchronize, edited, labeled]
  push:
    branches: [ main ]
    paths:
      - '../labels.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {} # Disable default permissions

jobs:

  label-syncer:
    name: Syncer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c # v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  labeler:
    name: Set labels
    needs: [label-syncer]
    permissions:
      contents: read
      pull-requests: write # Needed to add existing labels to PRs
    runs-on: ubuntu-latest
    steps:

    # Label based on modified files
    - name: Label based on changed files
      uses: actions/labeler@b8dd2d9be0f68b860e7dae5dae7d772984eacd6d # v6.2.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

  changelog-fragment:
    name: "Create changelog fragment"
    needs: [labeler]
    permissions:
      contents: write # Needed to create changelog fragment on PR
      pull-requests: write # Needed to create changelog fragment on PR
    runs-on: ubuntu-latest
    steps:
    - uses: ansys/actions/doc-changelog@a5b0351dc277d68c2dc1beca2d2674c7dfa4fc55 # v10.3.3
      with:
        token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
        use-conventional-commits: true
        use-default-towncrier-config: true
        bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
        bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}
